#!/opt/anaconda/Anaconda3-2022.05/bin/python
import numpy as np
from simpletraj.dcd.dcd import DCDReader

print("The script is used to calculate 'mean-square Ree'")
dcd = DCDReader('particle.dcd')
rees = []
for i in dcd:
    ree = i[-1][-1]-i[0][-1]
    rees.append(np.abs(ree))
#list装array
rees = np.array(rees)
rees_mean = np.mean(rees[-300:])
print(f"The mean Ree is: {rees_mean}")
