#!/opt/anaconda/Anaconda3-2022.05/bin/python
import numpy as np
from simpletraj.dcd.dcd import DCDReader
import os


def get_all_dir_path(path):
    dir_list = []
    for root, dirs, files in os.walk(path):
        for dir in dirs:
            dir_list.append(os.path.join(root, dir))
    return sorted(dir_list)
for file in sorted(get_all_dir_path(os.getcwd())):
    os.chdir(file)
    dcd = DCDReader('particle.dcd')
    pos = np.asarray([_.copy() for _ in dcd]).reshape(len(dcd), -1, 3)
    com = pos[0,-7:].mean(axis=0)
    v = pos[:, :500] - com[None, None, :]
    ids = np.argmin(np.linalg.norm(v, axis=-1), axis=-1)
    print(file)
    print(ids.mean())
    # print(ids.min())
# dcd = DCDReader('particle.dcd')
# pos = np.asarray([_.copy() for _ in dcd]).reshape(len(dcd), -1, 3)
# com = pos[0,-7:].mean(axis=0)
# v = pos[:, :400] - com[None, None, :]
# ids = np.argmin(np.linalg.norm(v, axis=-1), axis=-1)
# print(ids.mean())
# print(ids.min())
