#!/usr/bin/env python

import numpy as np
import sys
from xml_io import xml_parser
import gsd.hoomd
from simpletraj.dcd.dcd import DCDReader

def create_frames(_step, _pos, _box):
    s = gsd.hoomd.Snapshot()
    s.particles.N = natoms
    s.configuration.step = _step 
    s.configuration.box = _box 
    s.particles.position = _pos

    return s

fname_xml = sys.argv[1]
fname_dcd = sys.argv[2]

xml = xml_parser(fname_xml)
lx, ly, lz = xml.box
natoms = xml.nodes['position'].shape[0]
particles_types = np.unique(xml.nodes['type']).tolist()
particles_typeid = np.array([particles_types.index(_) for _ in xml.nodes['type']], dtype=int)

# build gsd
dcd = DCDReader(fname_dcd)

fname_out = fname_dcd.split('.')[0] + '.gsd'
f = gsd.hoomd.open(name=fname_out, mode='wb')

for i, frame in  enumerate(dcd):
    timestep = dcd.start_timestep + i * dcd.skip_timestep
    f.append(create_frames(timestep, frame, [lx, ly, lz, 0, 0, 0]))
    

