#!/opt/anaconda/Anaconda3-2022.05/bin/python
import numpy as np
from simpletraj.dcd.dcd import DCDReader
import os

N = int(input("N = (default 400)") or "400")
def get_all_dir_path(path):
    dir_list = []
    for root, dirs, files in os.walk(path):
        for dir in dirs:
            dir_list.append(os.path.join(root, dir))
    return sorted(dir_list)
for file in sorted(get_all_dir_path(os.getcwd())):
    os.chdir(file)
    dcd = DCDReader('particle.dcd')
    pos = np.asarray([_.copy() for _ in dcd]).reshape(len(dcd), -1, 3)
    com = pos[0,-7:].mean(axis=0)
    v = pos[:,N-1,:] - com[None,:]
    z_direction_mean = np.abs(v[-1000:,].mean(axis=0))
    print(z_direction_mean[-1])
    #print(file)
