#!/opt/Anaconda3-2021.11/bin/python
import numpy as np
from simpletraj.dcd.dcd import DCDReader
import os
import time

os.chdir("./")
#print(os.getcwd().split('/')[-1])
with open("rg2.log", "w") as f:
    f.write(" ")
os.system("echo -e '1:gpu=0' | galaTackle particle.0000000000.xml particle.dcd > galatackle.log")

with open("rg2.log", "r") as f:
    content = f.readlines()
contents = []
for i in content:
    contents.append(float(i.split()[2]))
ls = np.array(contents)
print("The mean Rg2(300 samples) is:", np.mean(ls[0:100]))
print("The mean Rg2(300 samples) is:", np.mean(ls[-300:]))
