#!/opt/anaconda/Anaconda3-2022.05/bin/python
import numpy as np
from simpletraj.dcd.dcd import DCDReader
import os
from xml_io import xml_parser

for file in sorted(get_all_dir_path(os.getcwd())):
    os.chdir(file)
    dcd = DCDReader('particle.dcd')
    pos = np.asarray([_.copy() for _ in dcd]).reshape(len(dcd), -1, 3)
    com = pos[0, (N + p * 7):(N + (p + 1) * 7)].mean(axis=0)
    v = pos[:, N - 1, :] - com[None, :]
    #v = pos[:, 0, :] - com[None, :]
    z_direction_mean = np.abs(v[-1000:, ].mean(axis=0))
    #print(file.split("/")[-1]+"---------------------------")
    print(z_direction_mean[-1])
    #print(file)
