#!/opt/anaconda/Anaconda3-2022.05/bin/python
import numpy as np
from simpletraj.dcd.dcd import DCDReader
import os

string2 = str(os.getcwd()).split("/")[-1].split("_")[-1][4:]
string2 = int(string2) * 10 - 1
print(string2)
def get_all_dir_path(path):
    dir_list = []
    for root, dirs, files in os.walk(path):
        for dir in dirs:
            dir_list.append(os.path.join(root, dir))
    return sorted(dir_list)
for file in sorted(get_all_dir_path(os.getcwd())):
    os.chdir(file)
    dcd = DCDReader('particle.dcd')
    pos = np.asarray([_.copy() for _ in dcd]).reshape(len(dcd), -1, 3)
    com = pos[0,-7:].mean(axis=0)
    v = pos[:,string2,:] - com[None,:]
    z_direction_mean = v[-500:,].mean(axis=0)
    #print(file)
    print(z_direction_mean[-1])
